blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /

mi:
    resource: "@MiBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
